export const AUTH_REQUEST: "AUTH_REQUEST" = "AUTH_REQUEST";
export const AUTH_REGISTER: "AUTH_REGISTER" = "AUTH_REGISTER";
export const AUTH_LOGIN: "AUTH_LOGIN" = "AUTH_LOGIN";
export const AUTH_LOGOUT: "AUTH_LOGOUT" = "AUTH_LOGOUT";
export const AUTH_FAILED: "AUTH_FAILED" = "AUTH_FAILED";
export const AUTH_CHECKED: "AUTH_CHECKED" = "AUTH_CHECKED";